name: shared_preferences_macos
description: macOS implementation of the shared_preferences plugin.
version: 0.0.1+3
homepage: https://github.com/luiz-simples/shared_preferences_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SharedPreferencesPlugin

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.14.1 <2.0.0"

dependencies:
  shared_preferences_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
